# Generated by Django 5.1.1 on 2024-12-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='catmupname_id',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='subcategorycitymup_id',
        ),
        migrations.AddField(
            model_name='complaints',
            name='barangay_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='city_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='date_endorse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='province_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='region_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='remind_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='time_acknowledge',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='time_endorse',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='compfile',
            field=models.ImageField(blank=True, null=True, upload_to='media/doc_file'),
        ),
    ]
