# Generated by Django 5.1.1 on 2024-12-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='date_endorse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='remind_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='time_acknowledge',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='time_endorse',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
