# Generated by Django 5.1.5 on 2025-01-23 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_remove_complaints_catmupname_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (3, 'moderator'), (2, 'compuser'), (4, 'sememoderator')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='Odsus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('passed_date', models.DateField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_endorse', models.DateField(blank=True, null=True)),
                ('remind_date', models.DateField(blank=True, null=True)),
                ('time_received', models.TimeField(blank=True, null=True)),
                ('time_acknowledge', models.TimeField(blank=True, null=True)),
                ('time_endorse', models.TimeField(blank=True, null=True)),
                ('region_name', models.CharField(blank=True, max_length=250, null=True)),
                ('province_name', models.CharField(blank=True, max_length=250, null=True)),
                ('city_name', models.CharField(blank=True, max_length=250, null=True)),
                ('barangay_name', models.CharField(blank=True, max_length=250, null=True)),
                ('complaint_number', models.IntegerField(default=0)),
                ('selfcomplaint_number', models.CharField(blank=True, max_length=50, null=True)),
                ('complainant_pace', models.CharField(default='No ticket number provided', max_length=250)),
                ('complaint_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('complaint_text', models.CharField(max_length=255)),
                ('complainttype', models.CharField(max_length=250)),
                ('clientdetails', models.CharField(blank=True, max_length=250, null=True)),
                ('noc', models.CharField(max_length=250)),
                ('endorseemp', models.CharField(blank=True, max_length=250, null=True)),
                ('complainant_fname', models.CharField(default='Anonymous', max_length=250)),
                ('complaindetails', models.TextField(blank=True)),
                ('compfile', models.ImageField(blank=True, null=True, upload_to='media/doc_file')),
                ('complaintdate_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('status', models.CharField(default='Closed', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.category')),
                ('subcategory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.subcategory')),
                ('userregid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.userreg')),
            ],
        ),
        migrations.CreateModel(
            name='OdsusRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True)),
                ('status', models.CharField(default='Closed', max_length=250)),
                ('remarkdate', models.DateTimeField(auto_now_add=True)),
                ('comp_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.complaints')),
            ],
        ),
    ]
