# Generated by Django 5.1.1 on 2025-02-01 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_alter_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.category'),
        ),
        migrations.AddField(
            model_name='userreg',
            name='subcategory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.subcategory'),
        ),
    ]
