# Generated by Django 5.1.1 on 2025-02-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_userreg_cat_id_userreg_subcategory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='subcategory_id',
        ),
        migrations.AddField(
            model_name='userreg',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsapp.category'),
        ),
        migrations.AddField(
            model_name='userreg',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsapp.subcategory'),
        ),
    ]
