# Generated by Django 5.1.1 on 2025-02-01 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_remove_userreg_cat_id_remove_userreg_subcategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsapp.category'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsapp.subcategory'),
        ),
    ]
