# Generated by Django 5.1.1 on 2025-02-04 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0007_customuser_cat_customuser_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='odsus',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.complaints'),
        ),
    ]
