# Generated by Django 5.1.1 on 2025-02-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0008_odsus_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odsus',
            name='complaint',
        ),
        migrations.AddField(
            model_name='odsus',
            name='complaints',
            field=models.ManyToManyField(related_name='odsus_entries', to='cmsapp.complaints'),
        ),
    ]
