# Generated by Django 5.1.1 on 2025-03-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0009_remove_odsus_complaint_odsus_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='cog',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='odsus',
            name='cog',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pacdcomplaints',
            name='cog',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
