# Generated by Django 5.1.5 on 2025-01-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0009_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'compuser'), (1, 'admin'), (3, 'moderator')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='pacdcomplaintremark',
            name='status',
            field=models.CharField(default='closed', max_length=250),
        ),
    ]
