# Generated by Django 5.1.1 on 2025-03-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0010_complaints_cog_odsus_cog_pacdcomplaints_cog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='cog',
        ),
    ]
