# Generated by Django 5.1.1 on 2025-03-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0011_remove_complaints_cog'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='cog',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
