# Generated by Django 5.1.5 on 2025-01-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'moderator'), (1, 'admin'), (2, 'compuser')], default=1, max_length=50),
        ),
    ]
