# Generated by Django 5.1.1 on 2025-03-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0013_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
