# Generated by Django 5.0.3 on 2024-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0014_remove_complaints_admin_complaints_userregid'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaint_text',
            field=models.CharField(default='Default Complaint Text', max_length=255),
            preserve_default=False,
        ),
    ]
