# Generated by Django 4.2.14 on 2024-07-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0016_complaints_complinant_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='complinant_fname',
            new_name='complainant_fname',
        ),
    ]
