# Generated by Django 5.1.1 on 2025-03-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0016_alter_complaints_date_endorse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date_endorse',
            field=models.DateField(blank=True, null=True),
        ),
    ]
