# Generated by Django 5.0.3 on 2024-08-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0017_rename_complinant_fname_complaints_complainant_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='selfcomplaint_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complainant_fname',
            field=models.CharField(default='Anonymous', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'compuser'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
