# Generated by Django 5.0.3 on 2024-08-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0020_alter_complaints_selfcomplaint_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'compuser')], default=1, max_length=50),
        ),
    ]
