# Generated by Django 5.0.3 on 2024-08-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0026_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complainant_pacenumber',
            field=models.CharField(default='No ticket number provided', max_length=250),
        ),
    ]
