# Generated by Django 5.0.3 on 2024-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0031_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaint_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'compuser')], default=1, max_length=50),
        ),
    ]
