# Generated by Django 5.0.3 on 2024-08-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0032_complaints_complaint_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='selfcomplaint_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
