# Generated by Django 5.0.3 on 2024-08-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0034_alter_complaints_complainant_pacenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complainant_pacenumber',
            field=models.CharField(max_length=255),
        ),
    ]
