# Generated by Django 5.0.3 on 2024-08-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0036_alter_complaints_complainant_pacenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='complainant_pacenumber',
        ),
    ]
