# Generated by Django 5.0.3 on 2024-08-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0037_remove_complaints_complainant_pacenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complainant_pace',
            field=models.CharField(default='No ticket number provided', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'compuser'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
