# Generated by Django 5.1.1 on 2024-09-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0042_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='passed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='time_received',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
