# Generated by Django 5.1.1 on 2024-09-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0053_complaints_barangay_complaints_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='stateid',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'compuser')], default=1, max_length=50),
        ),
    ]
