# Generated by Django 5.1.1 on 2024-10-09 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0059_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeaddress',
            name='purok',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='purok',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='street',
        ),
        migrations.RemoveField(
            model_name='completeaddress',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='completeaddress',
            name='street',
        ),
        migrations.AddField(
            model_name='completeaddress',
            name='barangay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.barangay'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaints',
            name='barangay',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.barangay'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='city',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.city'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='province',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.province'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'compuser')], default=1, max_length=50),
        ),
        migrations.DeleteModel(
            name='Purok',
        ),
    ]
